
version: '3.1'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "9306:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"
  web:
    image: haankan:latest
    restart: on-failure
    ports:
      - "9307:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=HaanKan.settings
    working_dir: /app

volumes:
  mysqldata: