
version: '3.1'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: User
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: Haankanwebapp
    ports:
      - "3306:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  mysqldata: