# Generated by Django 4.0 on 2022-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='apps',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
