# Generated by Django 4.0 on 2022-12-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0002_party_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='apps',
            field=models.CharField(max_length=300),
        ),
    ]
