# Generated by Django 4.0 on 2022-12-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0003_alter_party_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='party',
            name='apps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Party.apps'),
        ),
    ]
