# Generated by Django 4.0 on 2022-12-01 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0006_remove_party_member_party_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
