# Generated by Django 4.0 on 2022-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0007_alter_party_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='isApproved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
