# Generated by Django 4.0 on 2022-12-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0008_party_isapproved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('imageURL', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QrcodePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcodeImage', models.ImageField(upload_to=None)),
                ('qrcodeImageLink', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='apps',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='appImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Party.appimage'),
        ),
        migrations.AddField(
            model_name='party',
            name='qrcodepayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Party.qrcodepayment'),
        ),
    ]
