# Generated by Django 4.0 on 2022-12-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0009_appimage_qrcodepayment_alter_apps_name_apps_appimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodepayment',
            old_name='qrcodeImageLink',
            new_name='qrcodeImageURL',
        ),
    ]
