# Generated by Django 4.0 on 2022-12-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0011_appimage_imgename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='rating',
        ),
    ]
