# Generated by Django 4.0 on 2022-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0013_remove_appimage_imageurl_remove_appimage_imgename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appimage',
            name='image',
            field=models.ImageField(upload_to='Appimage'),
        ),
    ]
