# Generated by Django 4.0 on 2022-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0014_alter_appimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appimage',
            name='image',
            field=models.ImageField(null=True, upload_to='Appimage'),
        ),
    ]
