# Generated by Django 4.0 on 2022-12-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0015_alter_appimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='appImage',
            new_name='image',
        ),
    ]
