# Generated by Django 4.0 on 2022-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0016_rename_appimage_apps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='image',
            field=models.ImageField(null=True, upload_to='Appimage'),
        ),
        migrations.DeleteModel(
            name='AppImage',
        ),
    ]
