# Generated by Django 4.0 on 2022-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0017_alter_apps_image_delete_appimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='qrcodepayment',
        ),
        migrations.AddField(
            model_name='party',
            name='qrcodeImage',
            field=models.ImageField(null=True, upload_to='Partyqrcode'),
        ),
        migrations.AlterField(
            model_name='party',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='QrcodePayment',
        ),
    ]
