# Generated by Django 4.0 on 2022-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0019_alter_party_member_alter_party_qrcodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='qrcodeImage',
            field=models.ImageField(null=True, upload_to='Partyqrcode'),
        ),
    ]
