# Generated by Django 4.0 on 2022-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0021_banks_party_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='bankaccount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
