# Generated by Django 4.0 on 2022-12-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Party', '0022_party_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='member',
        ),
        migrations.AddField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
