# Generated by Django 4.0 on 2022-12-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Party', '0023_remove_party_member_party_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partymember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='Partymember',
            field=models.ManyToManyField(null=True, to='Party.Partymember'),
        ),
    ]
