# Generated by Django 4.0 on 2022-12-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0024_partymember_party_partymember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='Partymember',
            new_name='partymember',
        ),
    ]
