# Generated by Django 4.0 on 2022-12-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Party', '0026_remove_partymember_user_partymember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partymember',
            name='user',
        ),
        migrations.AddField(
            model_name='partymember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
