# Generated by Django 4.0 on 2022-12-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0027_remove_partymember_user_partymember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partymember',
            old_name='user',
            new_name='name',
        ),
    ]
