# Generated by Django 4.0 on 2022-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0028_rename_user_partymember_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partymember',
            name='name',
        ),
        migrations.AddField(
            model_name='partymember',
            name='fname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partymember',
            name='lname',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
