# Generated by Django 4.0 on 2022-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0030_rename_partymember_party_attendess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='attendess',
            field=models.ManyToManyField(blank=True, to='Party.Partymember'),
        ),
    ]
