# Generated by Django 4.0 on 2022-12-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0032_remove_party_attendess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partymember',
        ),
    ]
