# Generated by Django 4.0 on 2022-12-10 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Party', '0033_delete_partymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='owner',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
