# Generated by Django 4.0 on 2022-12-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Party', '0036_alter_party_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user'),
        ),
    ]
