# Generated by Django 4.0 on 2022-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0037_alter_party_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='owner',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
