# Generated by Django 4.0 on 2022-12-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0040_party_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Party_request',
        ),
    ]
