# Generated by Django 4.0 on 2022-12-15 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Party', '0042_alter_party_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='pending_members',
            field=models.ManyToManyField(related_name='pending_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
