# Generated by Django 4.0 on 2023-01-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0049_remove_party_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='image_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='qrcodeImage',
            field=models.ImageField(height_field='qrcode_height', null=True, upload_to='Partyqrcode', width_field='qrcode_width'),
        ),
    ]
