# Generated by Django 4.0 on 2023-01-28 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Party', '0052_party_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
