# Generated by Django 4.0 on 2023-01-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Party', '0056_alter_chatmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='evidence_of_payment',
            field=models.ImageField(height_field='image_height', null=True, upload_to='evidence_of_payment', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='party',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='auth.user'),
        ),
    ]
