# Generated by Django 4.0 on 2023-01-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0058_rename_evidence_of_payment_party_evidenceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidenceimage', models.ImageField(height_field='image_height', null=True, upload_to='evidence_of_payment', width_field='image_width')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Party.party')),
            ],
        ),
    ]
