# Generated by Django 4.0 on 2023-01-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0059_evidence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
