# Generated by Django 4.0 on 2023-01-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Party', '0060_delete_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='evidenceimage',
        ),
        migrations.RemoveField(
            model_name='party',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='party',
            name='uploader',
        ),
        migrations.CreateModel(
            name='EvidenceimageParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidenceimage', models.ImageField(height_field='image_height', null=True, upload_to='evidence_of_payment', width_field='image_width')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EvidenceimageParty', to='Party.party')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='auth.user')),
            ],
        ),
    ]
