# Generated by Django 4.0 on 2023-01-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0062_alter_evidenceimageparty_evidenceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
