# Generated by Django 4.0 on 2023-02-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0063_remove_chatmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='like_status',
        ),
    ]
