# Generated by Django 4.0 on 2023-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0064_remove_party_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='like_status',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
