# Generated by Django 4.0 on 2023-02-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0067_alter_party_priceaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='priceaverage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
