# Generated by Django 4.0 on 2023-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0068_alter_party_priceaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='isApproved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
