# Generated by Django 4.0 on 2023-02-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0069_apps_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='apps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Party.apps'),
        ),
    ]
