# Generated by Django 4.0 on 2023-02-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0070_alter_party_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='apps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Party.apps'),
        ),
    ]
