# Generated by Django 4.0 on 2023-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0075_alter_party_members_alter_party_pending_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='CategoryImage')),
            ],
        ),
    ]
