# Generated by Django 4.0 on 2023-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_bio_profile_dislikes_profile_like_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profliepic'),
        ),
    ]
