# Generated by Django 4.0 on 2022-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AlterField(
            model_name='news',
            name='desciption',
            field=models.TextField(max_length=500),
        ),
    ]
