# Generated by Django 4.0 on 2022-11-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_remove_news_image_alter_news_desciption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
