# Generated by Django 4.0 on 2022-12-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_newsimage_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='NewsImage'),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
