# Generated by Django 4.0 on 2022-12-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
