# Generated by Django 4.0 on 2022-12-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
