# Generated by Django 4.0 on 2022-12-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newimage')),
            ],
        ),
    ]
