# Generated by Django 4.0 on 2022-12-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Content', '0015_modelssss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='PostNews',
        ),
        migrations.DeleteModel(
            name='modelssss',
        ),
    ]
