# Generated by Django 4.0 on 2022-12-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0017_news_delete_newsimages_delete_postnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
