# Generated by Django 4.1 on 2022-12-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Content", "0020_alter_news_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="admin",
            new_name="writer",
        ),
    ]
