# Generated by Django 4.0 on 2022-12-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0021_rename_admin_news_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Newsimages'),
        ),
    ]
