# Generated by Django 4.0 on 2023-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0025_news_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desciption',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
