# Generated by Django 4.0 on 2023-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0026_alter_news_desciption_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desciption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
